name: ZHANGYUJie芯片组建
description: 一种轻量级的 websocket 的客户端。v不断v比我v我v哦卖我Ivor我能不并未v被v比热瓦北侧哦呜v弄热v浓而能从二五v哦任务吧v饿哦如不v饿哦
keywords:
  - ZHANGYUJI
  - 年号
license:                                   # GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD
logo: http://image.baidu.com/search/detail?ct=503316480&z=undefined&tn=baiduimagedetail&ipn=d&word=%E6%9D%8E%E6%98%93%E5%B3%B0&step_word=&ie=utf-8&in=&cl=2&lm=-1&st=undefined&hd=undefined&latest=undefined&copyright=undefined&cs=3778129713,3548713340&os=281524287,217802324&simid=4122203648,649407700&pn=0&rn=1&di=9240&ln=2108&fr=&fmq=1565256928867_R&fm=&ic=undefined&s=undefined&se=&sme=&tab=0&width=undefined&height=undefined&face=undefined&is=0,0&istype=0&ist=&jit=&bdtype=0&spn=0&pi=0&gsm=0&objurl=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fitem%2F201510%2F21%2F20151021214935_zLVKC.jpeg&rpstart=0&rpnum=0&adpicid=0&force=undefined&ctd=1565256930022^3_1263X610%1
source_file:
  - src/*.c

build_config:
  include:
    - include
  cflag: ""                             # C 编译器所需要要的编译参数
  define:                                      # 宏定义
    - CONFIG_USING_TLS

install:
  - dest: include
    source:
      - "include/librws.h"
