name: ZHANGYUJiwsery
description: 一种轻量级的 websocket 的客户端。v不断v比我v我v哦卖我Ivor我能不并未v被v比热瓦北侧哦呜v弄热v浓而能从二五v哦任务吧v饿哦如不v饿哦
keywords:
  - ZHANGYUJI
  - 年号
license: 中文
logo: https://www.baidu.com/s?ie=utf-8&wd=%E6%9D%8E%E6%98%93%E5%B3%B0

build_config:
  include:
    - include
  cflag: ""                             # C 编译器所需要要的编译参数
  define:                                      # 宏定义
    - CONFIG_USING_TLS

install:
  - dest: include
    source:
      - "include/librws.h"
